apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/publicEndpoints: '[{"addresses":["192.168.10.150"],"port":30502,"protocol":"TCP","serviceName":"hotelreservaties-app:hotel-frontend-nodeport","allNodes":true}]'
  name: hotel-frontend
  namespace: hotelreservaties-app
  uid: 4d30f305-77bd-48ab-9ea9-d1d8ea65d135
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-hotelreservaties-app-hotel-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-hotelreservaties-app-hotel-frontend
    spec:
      affinity: {}
      containers:
      - envFrom:
        - secretRef:
            name: frontend-env
            optional: false
        image: ghcr.io/everaertalexander/hotel-reservatie-frontend
        imagePullPolicy: Always
        name: hotel-frontend
        ports:
        - containerPort: 3001
          name: 3001tcp30502
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeName: everaert-alexander
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30