name: Workflow

on:
  push:
    tags:
      - 'v*.*.*'
    # branches:
    #   - 'feature/afwerking'
    
  workflow_dispatch:

jobs:
  Build:
    runs-on: self-hosted
    strategy:
      max-parallel: 1
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      # run: echo "RELEASE_VERSION=test" >> $GITHUB_ENV
    - name: Test
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
    - name: Get env
      run: | 
        echo NEXT_PUBLIC_BACKEND=$BACKEND >> ./.env
        echo NEXT_PUBLIC_FB_APIKEY=$APIKEY >> ./.env
        echo NEXT_PUBLIC_FB_APPID=$APPID >> ./.env
        echo NEXT_PUBLIC_FB_AUTHDOMAIN=$AUTHDOMAIN >> ./.env
        echo NEXT_PUBLIC_FB_MESSAGINGSENDERID=$MESSAGINGSENDERID >> ./.env
        echo NEXT_PUBLIC_FB_PROJECTID=$PROJECTID >> ./.env
        echo NEXT_PUBLIC_FB_STORAGEBUCKET=$STORAGEBUCKET >> ./.env
        echo NEXT_PUBLIC_SENTRY_DSN=$SENTRYDSN >> ./.env
        echo [auth] >> ./.sentryclirc
        echo $SENTRYCLIRC >> ./.sentryclirc
      env:
        BACKEND: ${{secrets.NEXT_PUBLIC_BACKEND}}
        APIKEY: ${{secrets.NEXT_PUBLIC_FB_APIKEY}}
        APPID: ${{secrets.NEXT_PUBLIC_FB_APPID}}
        AUTHDOMAIN: ${{secrets.NEXT_PUBLIC_FB_AUTHDOMAIN}}
        MESSAGINGSENDERID: ${{secrets.NEXT_PUBLIC_FB_MESSAGINGSENDERID}}
        PROJECTID: ${{secrets.NEXT_PUBLIC_FB_PROJECTID}}
        STORAGEBUCKET: ${{secrets.NEXT_PUBLIC_FB_STORAGEBUCKET}}
        SENTRYDSN: ${{secrets.NEXT_PUBLIC_SENTRY_DSN}}
        SENTRYCLIRC: ${{secrets.SENTRYCLIRC}}
    - name: Check env
      run: cat ./.env
    # - name: Install codegen
    #   run: |
    #     npm install --save graphql
    #     npm install --save @graphql-codegen/cli
    # - name: Run codegen
    #   run: npm run gen-types
    - name: Build docker image
      run: docker build -t ghcr.io/everaertalexander/hotel-reservatie-frontend:$RELEASE_VERSION .
    - name: Push docker image
      run: docker push ghcr.io/everaertalexander/hotel-reservatie-frontend:$RELEASE_VERSION
    - name: Check kubernetes
      run: kubectl get pods --namespace hotelreservaties-app
    - name: Update kubernetes image
      run: |
        kubectl set image deployment/hotel-frontend hotel-frontend=ghcr.io/everaertalexander/hotel-reservatie-frontend:$RELEASE_VERSION
