name: Workflow

on:
  push:
    branches:
      - feature/github-actions
    
  workflow_dispatch:

jobs:
  Build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Get env
      run: echo NEXT_PUBLIC_BACKEND=$BACKEND_URL >> ./.env
      env:
        BACKEND_URL: ${{secrets.NEXT_PUBLIC_BACKEND}}
    - name: Check env
      run: cat ./.env
    - name: Install codegen
      run: |
        npm install --save graphql
        npm install --save @graphql-codegen/cli
    - name: Run codegen
      run: npm run gen-types
    - name: Build docker image
      run: docker build -t ghcr.io/everaertalexander/hotel-reservatie-frontend .
    - name: Push docker image
      run: docker push ghcr.io/everaertalexander/hotel-reservatie-frontend
    - name: Check kubernetes
      run: kubectl get pods --namespace hotelreservaties-app
    - name: Create or update K8 deployment
      run: kubectl apply -f ./k8/frontend-manifest.yaml
    - name: Update kubernetes image
      run: |
        kubectl set image deployment/hotel-frontend hotel-api=ghcr.io/everaertalexander/hotel-reservatie-frontend
